import Layout from '../components/Layout'
import SEO from '../components/utils/SEO'
import Tokens from '../components/Home/Tokens'

const seoData = {
  title: 'Gallery View Brain',
  description:
    'Gallery Mint unique NFTs based on your ethereum address, generated by deep-learning algorithms.',
  keywords:
    'Gallery,nft,defi,ai,machine learning,deep learning,ethereum,crypto,blockchain,ETH',
}
export default function Gallery() {
  return (
    <Layout>
      <SEO data={seoData} />
      <Tokens />
    </Layout>
  )
}
