import Layout from '../components/Layout'
import SEO from '../components/utils/SEO'
import {Flex, Button, Heading } from '../components/ui'
import Generate from '../components/Home/Generate'
import React from 'react'
import { useMyToken } from '../hooks/tokens'
import { useEffect } from 'react'
import { useRouter } from 'next/router'

const seoData = {
  title: 'Generator View Brain',
  description:
    'Generator Mint unique NFTs based on your ethereum address, generated by deep-learning algorithms.',
  keywords:
    'Generator,nft,defi,ai,machine learning,deep learning,ethereum,crypto,blockchain,ETH',
}

const Generator: React.FC = () => {
  const { myToken, fetching } = useMyToken()
  const router = useRouter()

  useEffect(() => {

    if(myToken){

      router.push(`/token/${myToken.id}`)

    }

  }, [myToken, router, fetching])

  return (
    <Layout>
      <SEO data={seoData} />
        <Flex direction="column" align="center">
          <Heading
            textAlign="center"
          >Generator</Heading>
          {fetching ?
            <Button isLoading />
            :
            <Generate />
          }
        </Flex>
    </Layout>
  )
}

export default Generator
