import Layout from '../components/Layout'
import SEO from '../components/utils/SEO'
import { Flex, Heading } from '../components/ui'
import Generate from '../components/Home/Generate'
import React from 'react'
import { wrapUrqlClient } from '../lib/graphql'

const seoData = {
  title: 'Generator View Brain',
  description:
    'Generator Mint unique NFTs based on your ethereum address, generated by deep-learning algorithms.',
  keywords:
    'Generator,nft,defi,ai,machine learning,deep learning,ethereum,crypto,blockchain,ETH',
}

const Generator: React.FC = () => {
  return (
    <Layout>
      <SEO data={seoData} />
      <Flex direction="column" align="center" mt={75}>
        <Generate />
      </Flex>
    </Layout>
  )
}

export default wrapUrqlClient(Generator);
