import Layout from '../components/Layout'
import SEO from '../components/utils/SEO'
import Hero from '../components/Home/Hero'
import { Button, HStack } from '../components/ui'
import Link from 'next/link'
import React from 'react'

const seoData = {
  title: 'View Brain',
  description:
    'Mint unique NFTs based on your ethereum address, generated by deep-learning algorithms.',
  keywords:
    'nft,defi,ai,machine learning,deep learning,ethereum,crypto,blockchain,ETH',
}

export default function Home() {
  return (
    <Layout>
      <SEO data={seoData} />
      <Hero />
      <HStack spacing={8} display={{ base: 'none', md: 'flex' }}>
        <Link passHref href="/gallery">
          <Button
            as="a"
          >Discover</Button>
        </Link>
        <Link passHref href="/about">
          <Button
            as="a"
          >Learn more</Button>
        </Link>
      </HStack>
    </Layout>
  )
}
