import Layout from '../components/Layout'
import SEO from '../components/utils/SEO'
import { Button, Heading, Box, ActionButton } from '../components/ui'
import React, { useEffect } from 'react'
import { useWeb3 } from '../contexts/Web3Context'
import { wrapUrqlClient } from '../lib/graphql'
import { useRouter } from 'next/router'
import { defaultMyTokensQueryVariables, useMyTokens } from '../hooks/tokens'
import Tokens from '../components/Home/Tokens'
import Link from 'next/link'

const seoData = {
  title: 'My tokens Avant Garde',
  description:
    'My tokens Mint unique NFTs based on your ethereum address, generated by deep-learning algorithms.',
  keywords:
    'My tokens,nft,defi,ai,machine learning,deep learning,ethereum,crypto,blockchain,ETH',
}

const MyTokensPage: React.FC = () => {

  const { account, isConnecting } = useWeb3()
  const router = useRouter()
  const { tokens, fetching, error } = useMyTokens({
    ...defaultMyTokensQueryVariables,
    address: account?.address
  })

  useEffect(() => {

    if(!isConnecting && !account){

      router.push(`/`)

    }

  }, [isConnecting, account])

  if(!account) {

    return (<div></div>)

  }

  return (
    <Layout>
      <SEO data={seoData} />
      <Heading
        textAlign="center"
        mb={8}
      >Your items</Heading>
      <Tokens
        tokens={tokens}
        fetching={fetching}
        error={error}
        mine
      />
      <Box
        align="center"
        mt={12}
      >
        <Link passHref href="/gallery">
          <Button
            as="a"
            variant="outline"
            borderRadius="1rem"
            border="2px"
            borderColor="#3DDCC9"
            color="#3DDCC9"
            bgColor="white"
            px={24}
            rounded="full"
            _hover={{}}
            _active={{}}
          >Discover the gallery</Button>
        </Link>
      </Box>
    </Layout>
  )
}

export default wrapUrqlClient(MyTokensPage);
