import Layout from '../components/Layout'
import SEO from '../components/utils/SEO'
import Tokens from '../components/Home/Tokens'
import { Heading } from '../components/ui'
import React from 'react'
import { useWeb3 } from '../contexts/Web3Context'

const seoData = {
  title: 'My tokens View Brain',
  description:
    'My tokens Mint unique NFTs based on your ethereum address, generated by deep-learning algorithms.',
  keywords:
    'My tokens,nft,defi,ai,machine learning,deep learning,ethereum,crypto,blockchain,ETH',
}

export default function MyTokens() {

  const { account } = useWeb3();

  return (
    <Layout>
      <SEO data={seoData} />
      <Heading>Your items</Heading>
      <Tokens tokensProps={{ address: account.address}}/>
    </Layout>
  )
}
