import { useRouter } from 'next/router'
import Layout from '../../components/Layout'
import Token from '../../components/Home/Token'
import SEO from '../../components/utils/SEO'
const seoData = {
  title: 'Token View Brain',
  description:
    'Token Mint unique NFTs based on your ethereum address, generated by deep-learning algorithms.',
  keywords:
    'Token,nft,defi,ai,machine learning,deep learning,ethereum,crypto,blockchain,ETH',
}


export default function TokenPage() {
  const router = useRouter()
  const { id } = router.query

  if(!id){
    return <p>loqdinh</p>
  }
  return (
    <Layout>
      <SEO data={seoData} />
      <Token id={id} />
    </Layout>
  )
}
