import React from 'react'
import { Box, Heading, Center } from '../ui'

export default function Hero() {
  return (
    <Center as="section" my={8}>
      <Heading
        as="h4"
        textStyle="h4"
        textAlign="center"
        fontSize={{ base: '0.9rem', sm: '1rem', md: '1.2rem' }}
        maxWidth="50rem"
      >
        Mint unique NFTs based on your ethereum address, generated by
        deep-learning algorithms.
      </Heading>
    </Center>
  )
}
