import React from 'react'
import { Box, Heading, VStack } from '../ui'

export default function Hero() {
  return (
    <Box as="section" mb={12}>
      <VStack spacing={8} py={16} px={4}>
        <Heading
          as="h1"
          textStyle="h1"
          textAlign="center"
          layerStyle={'textGradient'}
          fontSize={{ base: '2rem', sm: '3rem', md: '4rem' }}
          maxWidth="50rem"
        >
          View Brain
        </Heading>
        <Heading
          as="h4"
          textStyle="h4"
          textAlign="center"
          fontSize={{ base: '0.9rem', sm: '1rem', md: '1.2rem' }}
          maxWidth="50rem"
        >
          Mint unique NFTs based on your ethereum address, generated by
          deep-learning algorithms.
        </Heading>
      </VStack>
    </Box>
  )
}
