import React from 'react'
import { ActionButton, Box, Button, Center, Heading, HStack, VStack } from '../ui'
import { TokenImage, ImageFrame } from '../ui/TokenImage'
import Link from 'next/link'
import { useWeb3 } from '../../contexts/Web3Context'
import { useToken } from '../../hooks/tokens'

export default function Hero() {
  const { account } = useWeb3();
  const { token } = useToken(account?.address)

  return (
    <VStack
      as="section"
      my={8}
      position="relative"
      minHeight="400px"
      align="center"
    >
      <Box
        position="absolute"
        opacity="0.8"
      >
        {token ?
          <Box opacity="0.5">
            <TokenImage size={350} avantGardeToken={token} />
          </Box>
          :
          <ImageFrame size={350} />
        }
      </Box>

      <Center
        h={350}
        flexDirection="column"
        mb={4}
      >
        <Heading
          as="h3"
          textStyle="h3"
          textAlign="center"
          fontSize={{ base: '1.2rem', sm: '1.6em', md: '1.8rem' }}
          position="relative"
          mb={2}
        >
          Mint unique NFTs based on your ethereum address
        </Heading>

        <Heading
          as="h3"
          textStyle="h3"
          textAlign="center"
          fontSize={{ base: '1.2rem', sm: '1.6rem', md: '1.8rem' }}
          position="relative"
        >
          Generated by deep-learning algorithms
        </Heading>
      </Center>

      <HStack spacing={8} justify="center" display={{ base: 'none', md: 'flex' }}>

        {
          token ?
            <Link passHref href={`/gallery}`}>
              <ActionButton
                as="a"
                w="12rem"
              >Gallery</ActionButton>
            </Link>
            :
            <Link passHref href="/generator">
              <ActionButton
                as="a"
                w="12rem"
              >Generate yours</ActionButton>
            </Link>
        }
        <Link passHref href="/about">
          <Button
            as="a"
            variant="outline"
            borderRadius="full"
            border="2px"
            borderColor="pupu"
            bgColor="white"
            px={12}
            rounded="full"
            _hover={{}}
            w="12rem"
          >Learn more</Button>
        </Link>

      </HStack>
    </VStack>
  )
}
